### ISSUE TITLE
review units and roundings

### ISSUE THREAD

**Issue by d4weed** [Vizzuality/iadb#17]
At times the figures are 0. not sure if this is because the value is very low and when rounding to 2 decimal places it dissappears, or because of the data.

Should review and see if we need 3 decimal places.

in the average graphs we should also round (right now they show like 10 decimal places)

maybe round to whatever in the queries so @davidsingal doesn't need to manage it in the client

**Comment by aagm** [comment]
solved, rounded to 3 decimals
